ALTER TABLE index_configs
    ADD COLUMN embedding_provider_key VARCHAR(64) NOT NULL
        DEFAULT 'openai-compatible',
    ADD COLUMN embedding_input_format_version VARCHAR(64) NOT NULL
        DEFAULT 'raw-text-v1',
    ADD COLUMN embedding_normalization_version VARCHAR(64) NOT NULL
        DEFAULT 'none-v1',
    ADD CONSTRAINT ck_index_configs_embedding_provider_key
        CHECK (btrim(embedding_provider_key) <> ''),
    ADD CONSTRAINT ck_index_configs_embedding_input_format
        CHECK (btrim(embedding_input_format_version) <> ''),
    ADD CONSTRAINT ck_index_configs_embedding_normalization
        CHECK (btrim(embedding_normalization_version) <> '');

CREATE TABLE embedding_artifacts (
    id UUID PRIMARY KEY,
    provider_key VARCHAR(64) NOT NULL,
    model_id VARCHAR(255) NOT NULL,
    model_revision VARCHAR(255) NOT NULL,
    purpose VARCHAR(32) NOT NULL,
    dimensions INTEGER NOT NULL,
    input_format_version VARCHAR(64) NOT NULL,
    normalization_version VARCHAR(64) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    vector_bytes BYTEA NOT NULL,
    vector_checksum VARCHAR(64) NOT NULL,
    byte_size INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_embedding_artifacts_cache_key UNIQUE (
        provider_key,
        model_id,
        model_revision,
        purpose,
        dimensions,
        input_format_version,
        normalization_version,
        input_hash
    ),
    CONSTRAINT ck_embedding_artifacts_provider CHECK (btrim(provider_key) <> ''),
    CONSTRAINT ck_embedding_artifacts_model CHECK (
        btrim(model_id) <> '' AND btrim(model_revision) <> ''
    ),
    CONSTRAINT ck_embedding_artifacts_purpose CHECK (purpose = 'CHILD_INDEX'),
    CONSTRAINT ck_embedding_artifacts_dimensions CHECK (
        dimensions BETWEEN 1 AND 4096
    ),
    CONSTRAINT ck_embedding_artifacts_versions CHECK (
        btrim(input_format_version) <> ''
        AND btrim(normalization_version) <> ''
    ),
    CONSTRAINT ck_embedding_artifacts_hashes CHECK (
        length(content_hash) = 64
        AND length(input_hash) = 64
        AND length(vector_checksum) = 64
    ),
    CONSTRAINT ck_embedding_artifacts_vector_size CHECK (
        byte_size = dimensions * 4
        AND octet_length(vector_bytes) = byte_size
    )
);

CREATE INDEX ix_embedding_artifacts_last_used
    ON embedding_artifacts (last_used_at, id);

CREATE INDEX ix_embedding_artifacts_content_hash
    ON embedding_artifacts (content_hash);

CREATE TABLE embedding_cache_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(16) NOT NULL,
    provider_key VARCHAR(64) NOT NULL,
    model_id VARCHAR(255) NOT NULL,
    model_revision VARCHAR(255) NOT NULL,
    actor_user_id UUID,
    deleted_artifacts BIGINT NOT NULL,
    freed_bytes BIGINT NOT NULL,
    reason VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_embedding_cache_events_action CHECK (action = 'CLEAR'),
    CONSTRAINT ck_embedding_cache_events_model CHECK (
        btrim(provider_key) <> ''
        AND btrim(model_id) <> ''
        AND btrim(model_revision) <> ''
    ),
    CONSTRAINT ck_embedding_cache_events_counts CHECK (
        deleted_artifacts >= 0 AND freed_bytes >= 0
    ),
    CONSTRAINT ck_embedding_cache_events_reason CHECK (btrim(reason) <> '')
);

COMMENT ON COLUMN embedding_cache_events.actor_user_id IS
    'Historical actor identifier intentionally has no users FK so audit survives account deletion';

CREATE INDEX ix_embedding_cache_events_model
    ON embedding_cache_events (
        provider_key, model_id, model_revision, created_at DESC
    );

CREATE TRIGGER reject_embedding_cache_event_mutation
    BEFORE UPDATE OR DELETE ON embedding_cache_events
    FOR EACH ROW EXECUTE FUNCTION reject_immutable_retrieval_row();
